### ISSUE TITLE
Anti-cheat software is detecting enchanted armor near beacons as "FastHealing"

### ISSUE THREAD

**Issue by kellysamareddit** [rDankMemes/Minecraft-Server-Support#1]
**Describe the bug**
Anti-cheat software is detecting enchanted armor near beacons as "FastHealing"

**To Reproduce**
1. Have fast healing armor
2. Be near a beacon
3. Get kicked for "FastHealing"

**Expected behavior**
It should not happen

**Screenshots**
N/A

**Your Environment**
 - Client Version: Any
 - OS: Any
 - Mods or Shaders: None

**Comment by elfahbeht-soop** [comment]
hmm we should fix this

**Comment by 0sp** [comment]
Add: I recently died to a glitch and lost all my items. When I respawned, I was kicked for FastHeal a few times near the beacon, even though the beacon was providing Resistance II, not Regeneration, and I had no armor on.

**Comment by kellysamareddit** [comment]
This is done.
