### ISSUE TITLE
Server not running Space Engineers

### ISSUE THREAD

**Issue by IndigoSoln** [rDankMemes/Minecraft-Server-Support#13]
**Describe the bug**
The server does not run Space Engineers. The server only serves Minecraft content. It does not have Space Engineers gamepley.

**To Reproduce**
1. Load Minecraft
2. Connect to the server
3. See attached screenshots

**Expected behavior**
The server should run Space Engineers

**Screenshots**
Experience on server
![minecraft server](https://user-images.githubusercontent.com/66527907/83950062-efc96200-a7f5-11ea-8a17-5346048b8f08.png)

Expected experience
![expected](https://user-images.githubusercontent.com/66527907/83950089-11c2e480-a7f6-11ea-8476-0c25646c9178.jpg)

**Your Environment**
 - Client Version: 1.15.2
 - OS Windows 10
 - Mods or Shaders OptiFine, SEUS RENEWED v1.0.1

**Additional context**
N/A

**Comment by kellysamareddit** [comment]
I agree. We need space engineers.
