### ISSUE TITLE
Switching items in inventory before teleport results in loss of item

### ISSUE THREAD

**Issue by IndigoSoln** [rDankMemes/Minecraft-Server-Support#14]
**Describe the bug**
Switching an item in the inventory during and slightly before a delayed teleport will cause the item to disappear

**To Reproduce**
1. Start a teleport (/home, /t spawn, /n spawn, etc.)
2. Open up your inventory using the hotkey,
3. Select an item in the matrix to "grab it"
4. Right before the teleport goes through, drop it on the hotbar

**Expected behavior**
The item is in your inventor xor hotbar when your teleport goes through.

**Screenshots**
N/A

**Your Environment**
 - Client Version: 1.15.2
 - OS Windows 10?
 - Mods or Shaders Optifine, SEUS-Renewed-v1.0.1 shader

**Additional context**
I'm 80% sure this happens because the teleport goes through server side when the item is in your "mouse hand" and doesn't technically exist in your inventory while it's like that. This just wasn't noticed before because teleports were instant. This probably also happens when you teleport while holding the item in your house hand.

**Comment by NUTsTUN** [comment]
Just ran a quick test, and when the item is being held by the mouse while the teleport occurs, the item will be dropped at your current location.

My Test:

1. Type /spawn

2. Open inventory

3. Click on item (leaf block)

4. Teleport to spawn -> Item is not in inventory

5. Type /back

6. Teleport back, observe item laying on ground.

This appears to be a non-issue.

**Comment by IndigoSoln** [comment]
@kellysamareddit Yes this appears to be an non issue **if** you think that driving back to pick up the muffler that fell off your car is not an issue to it falling off when you hit a pothole.

Just call it what it is: a side effect that you don't know how to work around.
