### ISSUE TITLE
Request for list of plugins.

### ISSUE THREAD

**Issue by mandjevant** [rDankMemes/Minecraft-Server-Support#15]
**Is your feature request related to a problem? Please describe.**
Would like to do some research on some of the bugs. For example the problems with witch spawning. This might relieve some of the load and I find it interesting to do.

**Describe the solution you'd like**
I request a list of plugins preferably with their version so I can adequately research the underlying problems.

**Additional context**
Feel free to send them privately - Pim

**Comment by elfahbeht-soop** [comment]
![image](https://user-images.githubusercontent.com/37937312/85425782-3ed5fd80-b53f-11ea-8437-21e3cf46700b.png)
