### ISSUE TITLE
An invisible force pushes players off blocks while digging down

### ISSUE THREAD

**Issue by mandjevant** [rDankMemes/Minecraft-Server-Support#16]
**Describe the bug**
An invisible force pushes you off blocks while digging down.

**To Reproduce**
1. Build a 1 block dirt/stone tower.
2. Stand on top and dig down.
3. An invisible force will push you to the side and eventually, will push you off the tower.

**Expected behavior**
The player should be able to dig down without being pushed off the tower.

**Screenshots**
N/A

**Your Environment**
 - Client Version: 1.13.2
 - OS: Windows
 - Mods or Shaders: None

**Comment by NUTsTUN** [comment]
I was able to replicate this with a Eff 5 Diamond pick. From some research this looks to be a [Minecraft](https://bugs.mojang.com/browse/MC-168488) bug, not the servers.

**Comment by mandjevant** [comment]
@NUTsTUN The linked article references a bug from 1.14.
> This has happened since at least 1.14 and seems unchanged in 1.

**Comment by justin-venetucci** [comment]
Closed due to being minecraft bug.  Unfortunately, we can not solve these on our end
