### ISSUE TITLE
Balance plugin not functioning

### ISSUE THREAD

**Issue by mandjevant** [rDankMemes/Minecraft-Server-Support#18]
**Describe the bug**
The balance plugin is not functioning. /money, /bal, /balance etc. Only /baltop functions properly.

**To Reproduce**
1. Type /bal or /money or /balance.
2. An error will appear.

**Expected behavior**
The balance plugin should actually function.

**Screenshots**
N/A

**Your Environment**
 - Client Version: 1.13.2
 - OS: Windows
 - Mods or Shaders: None

**Additional context**
I have seen multiple announcements that this was fixed. However, it does not work for the player. If the commands do work for mods+, look into permission issues.

**Comment by elfahbeht-soop** [comment]
/bal works on the server with Tester and SubMod roles now.
