### ISSUE TITLE
General help | Onboarding flow

### ISSUE THREAD

**Issue by mandjevant** [rDankMemes/Minecraft-Server-Support#19]
**Is your feature request related to a problem? Please describe.**
For new players, it is difficult to find their way around. There are many plugins and even more commands. 

**Describe the solution you'd like**
A general help page or onboarding flow for the general plugins in the server. Could be added as a webpage.

**Describe alternatives you've considered**
A shorter help command that explains the basics in chat.

**Comment by GamationOnGithub** [comment]
this exists as part of the sub's wiki, the towny, chat, and economy plugins are all explained there. we can open that wiki up with the server and add a link to it as part of /help commands
