### ISSUE TITLE
Random teleportation while flying

### ISSUE THREAD

**Issue by jotaps2609** [rDankMemes/Minecraft-Server-Support#2]
So lately I have been end busting, quite a lot as some may say and I have noticed a really strange bug, while flyin truh end cities you will get randomly teleported to the ground and land, the problem is, when you are above the void you will get teleported to the are where if you go 1 block down you start taking damage, I have almost lost all my stuff due to this bug.

**Comment by kellysamareddit** [comment]
Closing as duplicate.
