### ISSUE TITLE
It is possible to accidentally clip into blocks and die to suffocation damage

### ISSUE THREAD

**Issue by 0sp** [rDankMemes/Minecraft-Server-Support#20]
**Describe the bug**
When you have the levitation effect and there is a ceiling above you, pressing shift or the equivalent crouch button will visually move you down a little and clip you into the block above you, causing you to take suffocation damage until the levitation wears out.

**To Reproduce**
1. Locate an end city
2. Get hit by a shulker
3. Crouch when there is something above your head

**Expected behavior**
Nothing should happen.

**Screenshots**

**Your Environment**
 - Client Version: 1.15.2
 - OS: Mint
 - Mods or Shaders: OptiFine

**Additional context**

**Comment by justin-venetucci** [comment]
Have researched.  Is 1.13 MC bug.  Can not fix this ourselves.  Closing
