### ISSUE TITLE
Random teleportation glitch while flying

### ISSUE THREAD

**Issue by jotaps2609** [rDankMemes/Minecraft-Server-Support#3]
**Describe the bug**

**To Reproduce**
1. Go to an end city
2. Fly, I would say, a max of 50 blocks around ut
3. Get teleported to the block below you, or void barrier in case of being above the void

**Expected behavior**
Not get teleported to the ground/void

**Your Environment**
 - Client Version: [e.g. 1.13.2]
 - Windows
 - Optifine, no texture packs and no shaders, connected textures on.

**Comment by elfahbeht-soop** [comment]
it's elytra

**Comment by jotaps2609** [comment]
Yes

**Comment by GamationOnGithub** [comment]
this is because of spartan being gay (not a glitch), but it's not something we can really control without disabling elytra hack checks - i'll leave this to other admins to decide
