### ISSUE TITLE
Change the rank of SubMod to something that doesn't have 'Mod' in the name

### ISSUE THREAD

**Issue by 0sp** [rDankMemes/Minecraft-Server-Support#36]
**Is your feature request related to a problem? Please describe.**
Some people have gotten confused and thought submods are junior mods of the server when in actuality we don't do any moderating on the server. This problem will likely get worse once the server goes public

**Describe the solution you'd like**
Change 'SubMod' to either something nondescript, like "gay", or something really specific, like "Subreddit Mod"

Also there's only like 4 of us pls give priorityqueue

**Describe alternatives you've considered**
Explaining to everybody that we're not server mods

**Additional context**

**Comment by justin-venetucci** [comment]
Anything longer than submod is way too long.  See below.  Closed until a better name suggestion is brought to table
![image](https://user-images.githubusercontent.com/40038846/91756132-41d21780-eb9a-11ea-8c5c-378bf1c29265.png)
