### ISSUE TITLE
/t outpost list 2

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#41]
**Describe the bug**
/t outpost list 2 returns "[Towny] null"

**To Reproduce**
1. Be in a town with 11+ outposts.
2. Type /t outpost list 2
3. See error

**Expected behavior**
Like /t outpost list, which displays the first page of outposts, /t outpost list 2 should display the second page of outposts.

**Screenshots**
https://imgur.com/a/6BAWf6M

**Your Environment**
 - Client Version: 1.13.2
 - OS: Linux
 - Mods or Shaders: Litematica

**Additional context**
/t outpost list 3 works.
This used to work a while ago.

**Comment by justin-venetucci** [comment]
gam can u look into this? I tried to fix but am stumped

cc @GamationOnGithub
