### ISSUE TITLE
Increase upkeep

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#42]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am waiting to loot an abandoned town but then I find out it still has several more years of life because it has so much money in it's bank

**Describe the solution you'd like**
Increase the upkeep

**Describe alternatives you've considered**
none

**Additional context**
As of now, Susanville has around 100,000 karma in it's bank and has an upkeep of 100 karma. It will go bankrupt in 2.7 years.
As of now, Downtown Coolsville has around 8 million karma in it's bank and has an upkeep of 100 karma. It will go bankrupt in 245.5 years.
Small towns have like an upkeep of 10.

And yes- real-time years, not in-game years.

**Comment by smeegle5000** [comment]
agreed, i too would love to ~~loot~~ see the upkeep go up, i feel it should go up with the amount of players in the town
