### ISSUE TITLE
changing servers will announce your presence

### ISSUE THREAD

**Issue by smeegle5000** [rDankMemes/Minecraft-Server-Support#45]
**Describe the bug**
when you change server, it will say "[player] is coming from [previous lobby]"

**To Reproduce**
be in a different server lobby, say egg
/server jakku
it will say that you are coming from egg in chat

**Expected behavior**
it to not say that

**Additional context**
might be to do with /vanish but not sure

**Comment by justin-venetucci** [comment]
Thought I fixed this but didn't work.  Kelly will need to look into bungee.  Estimated time of fix: EOD today. 

CC @kellysamareddit
