### ISSUE TITLE
togglable modchat

### ISSUE THREAD

**Issue by smeegle5000** [rDankMemes/Minecraft-Server-Support#46]
**Is your feature request related to a problem? Please describe.**
people have slipped up and accidentally typed the message in normal chat, forgetting to put /mod at the start of the message 

**Describe the solution you'd like**
some sort of toggle that directs all your messages to the modchat, and possibly another toggle to turn off normal chat, to prevent cluttering

**Comment by justin-venetucci** [comment]
Solved.  Investigating possible bug, but should work now.

"/channel join mod write" gets you into mod chat
"/channel join mod read" gets you out.

Can be abbreviated to "/ch j mod [write/read]"
working on getting "/mod" to toggle mod chat
