### ISSUE TITLE
Flying glitch

### ISSUE THREAD

**Issue by jotaps2609** [rDankMemes/Minecraft-Server-Support#5]
**Describe the bug**
Yes another one, this one probably as to do with the fact that I'm 280k blocks into the end but sometimes I kind of go into an invisible barrier and it keeps pushing me back into the same block, doesnt matter if I go up, down, back from where I came or keept going.

**To Reproduce**
1. Go to the end
2. Fly
3. Go into barrier?

**Expected behavior**
Fly in a straight line (cause I'm not gay) and dont get pushed back.

**Your Environment**
 - 1.13.2
 - Windows
 - Optifine

**Comment by NUTsTUN** [comment]
A few questions:

Do you know the exact coordinates this occurred?

Were you able to walk?

Were all the chunks loaded around you?

**Comment by justin-venetucci** [comment]
Until @NUTsTUN's questions are answered, this will be closed.
