### ISSUE TITLE
Spawn boundary can teleport you into caves

### ISSUE THREAD

**Issue by goldninjaI** [rDankMemes/Minecraft-Server-Support#52]
**Describe the bug**
The teleportation that keeps you inbounds at /spawn can teleport you into caves below.

**To Reproduce**
1. Go to '800, -2000'
Right around this cactus
![image](https://user-images.githubusercontent.com/71352291/93264223-cc0ea400-f774-11ea-8c3b-f531176c1159.png)

2. Keep going out of bounds
3. See error

**Expected behavior**
Teleport a few blocks back

**Screenshots**
![image](https://user-images.githubusercontent.com/71352291/93263931-6de1c100-f774-11ea-97b9-00ede64137f0.png)

**Your Environment**
 - Client Version: [e.g. 1.16.3]
 - OS Windows
 - Mods or Shaders OptiFine

**Comment by justin-venetucci** [comment]
After investigation both internally and on the web, I see no plausible way to fix.  For now, I will mark as no plan to fix
