### ISSUE TITLE
Ejecting a villager out of a bed sets your /home bed

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#54]
**Describe the bug**
Sometimes you want to make a villager get out of a bed. You do this by right clicking the bed. However, this action also sets your home to this bed.

**To Reproduce**
1. Go to your home bed
2. Right click it to set your /home bed
3. Go to a sleeping villager
4. Right click the bed to make it get out.
5. Type /home bed
6. You will not be teleported to your home bed.

**Expected behavior**
I expect to teleport to my home bed, not the bed I got the villager out of.

**Screenshots**
none

**Your Environment**
 - Client Version: 1.16.3
 - OS Linux
 - Litematica 1.16.3

**Additional context**
none

**Comment by GamationOnGithub** [comment]
this is a vanilla mechanic
