### ISSUE TITLE
Farm plots have incorrect permissions.

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#57]
**Describe the bug**
One of the plot types you can set with the Towny plugin is the Farm plot. In these plots, the specified groups (residents, outsiders, etc) can harvest and plant crops.
However, currently players can only harvest pumpkins and pumpkin stems.

**To Reproduce**
1. Go to a farm plot
2. Try to break/place crops
3. See error

**Expected behavior**
Players should have permissions to harvest/plant:
Carrots
Potatoes
Sugar cane
Cactus
Beetroot
Nether wart
Cocoa bean
Melon

**Screenshots**
https://i.imgur.com/EXs6UxA.png

**Your Environment**
 - Client Version: 1.16.3
 - OS Linux
 - Mods or Shaders Litematica

**Additional context**
https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#farm-plots

**Comment by justin-venetucci** [comment]
Just verified that config.yml has all of those minus the Nether wart.  Adding that, but the towny documentation says

> Who can build/destroy these blocks is still determined by the plot's perm line seen in the /plot perm screen. This means that if B=rnao, anyone can plant/place the allowed blocks in the plot. If the B=r--- then only town residents can plant/place the allowed blocks.

Double check your plot settings and let us know if that's the issue or not.  Thanks!

**Comment by justin-venetucci** [comment]
Update: it says
List of blocks which can be modified on farm plots, as long as player is also allowed in the plot's '/plot perm' line.
**setting the perms to allow building and destroying is necessary, but it will only allow them to build/destroy the designated blocks. Hope this helps!**

**Comment by aco4** [comment]
The plot settings have build and destroy perms on for residents. I asked a resident to attempt to break wheat in a farm plot. It did not work.
