### ISSUE TITLE
Dyed and washed leather armor can't be sold in /spawn shops

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#59]
**Describe the bug**
Leather armor that has been dyed/washed can't be sold in /spawn shops. It doesn't matter if the leather armor is blue, red, or washed back to default color; the shop will not allow it.

**To Reproduce**
1. Get a leather chestplate
2. Dye it
3. Wash it in a cauldron
4. Try to sell it
5. See error

**Expected behavior**
Default color leather armor should be able to be sold, as well as colored armor.

**Screenshots**
https://i.imgur.com/QsmUYzS.png The dyed-and-washed leather chestplate. Notice how it has 3 NBT tags.

https://i.imgur.com/UOxBM8N.png A regular, never-dyed leather chestplate. Only 2 NBT tags.
https://i.imgur.com/Wa0Oasz.png The dyed-and-washed leather chestplate cannot be sold.
https://i.imgur.com/d2OkQE9.png The regular, never-dyed leather chestplate can be sold.

**Your Environment**
 - Client Version: 1.16.3
 - OS Linux
 - Mods or Shaders Litematica

**Additional context**
Enchanted armor and damaged armor cannot be sold, either.

**Comment by justin-venetucci** [comment]
Looks like we would have to create a new shop for each of those additional types of NBT tags.  I'll look into it but this may be a largely impractical fix if you need a new shop for each color of armor after it's been dyed manually

**Comment by justin-venetucci** [comment]
lol edit i forgot all the physical shops are gone now.  So let us know if this persists with the new shops, but not sure how much we can do.
