### ISSUE TITLE
Towny Plot Groups

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#6]
**Bug description**
When trying to create a plot group with the command _/plot group add <group name>_, the command returns an error: "_[Towny] Invalid 'group' property._"

1. Create a town
2. Stand in a claimed chunk
3. Type /plot group add Highlands

**Expected behavior**
The plot you are standing in should have been added to a group called Highlands.

**Screenshots**
n/a

**Your Environment**
 - Client Version: 1.13.2
 - OS: Linux
 - Mods or Shaders: none

**Additional context**
See attached screenshot from the Official Towny Wiki on their github
![Screenshot from 2020-05-28 10-27-42](https://user-images.githubusercontent.com/53398545/83931480-f9f24e80-a76a-11ea-8cd3-db29bd2e6746.png)

**Comment by elfahbeht-soop** [comment]
This is in a newer version of towny than what we have. We have version 0.95.1.0, this feature was introduced in 0.96 

https://github.com/TownyAdvanced/Towny/releases/tag/0.96.0.0

**Comment by elfahbeht-soop** [comment]
More accurate link: https://github.com/TownyAdvanced/Towny/releases/tag/0.96.0.0for1.13.2
