### ISSUE TITLE
Instant mining is accompanied by multiple block breaking visual glitch.

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#63]
**Describe the bug**
When instantmining, the blocks seem to break multiple times (visually and audibly).

**To Reproduce**
1. Give yourself Haste II and a Efficiency V diamond pickaxe.
2. Create a large cube of stone.
3. Mine it and see error.

**Expected behavior**
Each block should break once.

**Screenshots**
none

**Your Environment**
 - Client Version: 1.16.3
 - OS: Linux
 - Mods or Shaders: Litematica

**Additional context**
Does not affect durability.

**Comment by justin-venetucci** [comment]
Try disabling shaders / optifine @aco4.  My guess is it is a vanilla bug though.  Haste II can cause some wacky visuals sometimes regardless of client.  Keep us posted
