### ISSUE TITLE
Add a plugin that will ping players when they are mentioned in chat

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#7]
**Is your feature request related to a problem? Please describe.**
I go afk sometimes with Minecraft running in the background, it would be nice to know if someone mentions you.

**Describe the solution you'd like**
When someone says your name or nickname in chat, a pling sound will happen. Similar to Discord.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by justin-venetucci** [comment]
Chatcontrol offers this but it looks like only with /r and /tell.  We have those on at the moment.  Not sure if chatcontrol would work with this or if it would have to be another medium...

**Comment by justin-venetucci** [comment]
Wait JK.  
https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-15-2.271/
> Can specify a prefix that is necessary to get notified (e.g @kangarko)

**Comment by WolfDWyc** [comment]
I already made a plugin for that in public chats though, theirs is probably better

**Comment by justin-venetucci** [comment]
@WolfDWyc status?

**Comment by WolfDWyc** [comment]
@Commander-ISA i can dm the jar if you want

**Comment by kangarko** [comment]
I have been tagged here, do you guys need our help setting up ChatControl's sound notify?
