### ISSUE TITLE
Replace current join messages with danker ones

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#72]
**Is your feature request related to a problem? Please describe.**
The current join messages are generic and undank. I want ones that represent the server

**Describe the solution you'd like**
I can't come up with any good ones, so add a #suggest-join-messages channel for people to suggest funny ones

**Describe alternatives you've considered**
Keep the current ones and be lame

**Additional context**
none

**Comment by GamationOnGithub** [comment]
done
