### ISSUE TITLE
Modify player deaths/money

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#73]
**Is your feature request related to a problem? Please describe.**
Currently, players lose 10% of their money on death (Jakku). Here are some claims that try and resolve this issue:

1. Losing 10% money on death is too much.
I disagree. dying should result in a consequence that cannot be easily avoided with /back. Also if you die it's really your fault. However, people are upset about losing so much money, so maybe it is worth looking into alternatives.

2. Losing 10% money on death is too much; however, players can use the town bank to store their money. Mayors can grant roles to players that allows them to withdraw.
I disagree:
- Players with no roles will not be able to store their money.
- It is shared. A player can deposit a million dollars and someone else can take it out.
- The town bank belongs to the town, not the residents. Taxes collected from players go to the town bank. Upkeep is taken from the town bank.

3. Losing 10% money on death is too much; implement physical notes that players can convert their money into (and store)
I agree. This would cause issues if there is a dupe, but a dupe would be extremely bad regardless if they were duping notes. (they could just dupe god armor, etc.) Additionally, money in item form can be very useful in fun contraptions like gambling machines, etc.

The only issue is that the server is close to soft release and implementing new things is iffy.

**Describe the solution you'd like**
I would either like the system to stay the way it is, or implement #3.

**Describe alternatives you've considered**
#3

**Additional context**
none

**Comment by GamationOnGithub** [comment]
We will not be adding physical notes, at all. This doesn't mean something won't change relating to this but it won't be changing soon.
