### ISSUE TITLE
Some players have spaces in front of their names

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#85]
**Describe the bug**
When viewing the tablist, some players have spaces in front of their names, as if it was a prefix. I think this is also true with player nametags (the ones above players' heads).

**To Reproduce**
1. View tab
3. See error

**Expected behavior**
There should be no space

**Screenshots**
https://cdn.discordapp.com/attachments/601549201867800587/781626027759239239/2020-11-26_16.02.22.png

**Your Environment**
 - Client Version: 1.16.4
 - OS Linux
 - Mods or Shaders Litematica

**Additional context**
none

**Comment by elfahbeht-soop** [comment]
When was that screenshot taken?

**Comment by aco4** [comment]
> When was that screenshot taken?

November 11, however I was in lobby yesterday and had the bug occur. That was actually what reminded me to submit this bug report.
