### ISSUE TITLE
Boats :trollface: 

### ISSUE THREAD

**Issue by RandomPrimary2004** [rDankMemes/Minecraft-Server-Support#95]
**Describe the bug**
dismounting boats leads to getting stuck on the hit-box, unable to move off of them. 

**To Reproduce**
1. join the earth server on 1.19.4
2. place a boat in a body of water at least 2x2 blocks wide
3. make sure the boat isn't touching any non-water blocks
4. get in the boat
5. dismount with left-shift
6. profit

**Expected behavior**
you dismount the boat and stand atop it instead of driving it

**Screenshots**

https://user-images.githubusercontent.com/111301912/230653833-4282dcb5-68a5-496a-907f-68e86ed4917f.mp4

**Your Environment**
 - Client Version: 1.19.4

 - OS: Archlinux on kernel `6.2.9-arch1-1 (64-bit)`
 - Version: Minecraft 1.19.4
 - Mods or Shaders: ![mods](https://user-images.githubusercontent.com/111301912/230652997-d8bf5f19-6f8b-4605-b70f-1475f96b577f.png)

**Additional context**
Client server lag may cause this issue. i have 80 ping on average.

**Comment by smeegle5000** [comment]
please retest as a server update has taken place since

**Comment by RandomPrimary2004** [comment]
I can no longer reproduce the issue since the server update. it seems to be fixed. thanks smeeg
