### ISSUE TITLE
Music Disks continue to play after removing them

### ISSUE THREAD

**Issue by RandomPrimary2004** [rDankMemes/Minecraft-Server-Support#96]
**Describe the bug**
Music from in-game music discs continues to play until the song is over no matter if the disc is removed or if the player is destroyed

**To Reproduce**
1. Place a jukebox
2. insert a disk by right clicking
3. remove the disk or destroy the jukebox
4. profit

**Expected behavior**
When the music disk is removed or the jukebox is destroyed, the music should end instead of continuing. 

**Screenshots**

https://user-images.githubusercontent.com/111301912/230706564-f4a4664d-7602-490d-87d5-b717165331c1.mp4

**Your Environment**
 - Client Version: 1.19.4
 - OS Archlinux 6.2.9-arch1-1 (64-bit)
 - Mods or Shaders: 
![mods](https://user-images.githubusercontent.com/111301912/230706618-d8a51237-e5d4-4750-b05b-41a0e6010685.png)

**Comment by smeegle5000** [comment]
fixed by updating server version to 1.19.4 instead of cheating and using viaversion (fake 1.19.4)
